### ISSUE TITLE
[MobFoxAd cleanupWebView] issue

### ISSUE THREAD

**Issue by MattiaConfalonieri** [mobfox/MobFox-iOS-SDK#26]
I use mobFox in mediation inside AdMob.

i have the follow crash.
[MobFoxAd cleanupWebView]

Here the stack trace.

`Crashed: com.apple.main-thread
0  libobjc.A.dylib                0x31dd7f76 objc_msgSend + 21
1  PiccoleRicette                 0x68f005 -[MobFoxAd cleanupWebView] (MobFoxAd.m:1083)
2  PiccoleRicette                 0x68ee3f -[MobFoxAd didEnterBackground:] (MobFoxAd.m:1066)
3  CoreFoundation                 0x24511f15 __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
4  CoreFoundation                 0x2446ce4d _CFXNotificationPost + 1800
5  Foundation                     0x251a1ec1 -[NSNotificationCenter postNotificationName:object:userInfo:] + 76
6  UIKit                          0x27c65d55 -[UIApplication _handleApplicationDectivationWithScene:shouldForceExit:transitionContext:completion:] + 980
7  UIKit                          0x27c6cf75 __88-[UIApplication _handleApplicationLifecycleEventWithScene:transitionContext:completion:]_block_invoke + 76
8  UIKit                          0x27c6cf21 -[UIApplication _handleApplicationLifecycleEventWithScene:transitionContext:completion:] + 360
9  UIKit                          0x27c621df -[UIApplication scene:didUpdateWithDiff:transitionContext:completion:] + 474
10 FrontBoardServices             0x2acc21d5 __80-[FBSSceneImpl updater:didUpdateSettings:withDiff:transitionContext:completion:]_block_invoke_2 + 40
11 FrontBoardServices             0x2acd10c9 __31-[FBSSerialQueue performAsync:]_block_invoke + 12
12 CoreFoundation                 0x2451fffd __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
13 CoreFoundation                 0x2451f2c1 __CFRunLoopDoBlocks + 216
14 CoreFoundation                 0x2451de1b __CFRunLoopRun + 1714
15 CoreFoundation                 0x2446ab31 CFRunLoopRunSpecific + 476
16 CoreFoundation                 0x2446a943 CFRunLoopRunInMode + 106
17 GraphicsServices               0x2b84a051 GSEventRunModal + 136
18 UIKit                          0x27a606f1 UIApplicationMain + 1440
19 PiccoleRicette                 0x150323 main (main.m:17)
20 libdyld.dylib                  0x32367aaf <redacted> + 2`

**Comment by shimisheetrit** [comment]
Can you reproduce this crash?
If it's possible, please send us the steps for reproducing it. thanks.

**Comment by MattiaConfalonieri** [comment]
Unfortunately i can't, for now only iOS 8.x seems affected by this bug, and i don't have device with that iOS.

I suppose the bug appear when user click on adv and the app go in background...

**Comment by shimisheetrit** [comment]
I'll try to reproduce it on iOS 8.x. thanks.

**Comment by shimisheetrit** [comment]
We didn't reproduce this crash, but we did some code that should fix it.
New version v3.0.8 was released. Let us know if it works for you.

**Comment by MattiaConfalonieri** [comment]
Thanks, i have send a new version to apple right now, in 4/5 the new version go online... I keep you updated.

**Comment by MattiaConfalonieri** [comment]
Unfortunately the update don't fix the problem... 

[http://crashes.to/s/7a8bac3d502](url)

**Comment by nabriski** [comment]
Hi,

In v3.1.0 this code was commented (as it's not mandatory anyway). Can you please try it now?
As I said before, unfortunately, we cannot reproduce it here.

I apologize for you inconvenience

**Comment by MattiaConfalonieri** [comment]
As you can see the issue persist with the version 3.1.0

http://crashes.to/s/32220f426ac

**Comment by nabriski** [comment]
Hi,

We finally found it, will take us a few more weeks to release a fix.

**Comment by nabriski** [comment]
fixed in 3.1.6
